/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";
import WhoWeAre from "./WhoWeAre";
import OurMission from "./OurMission";
import CustomerCare from "./CustomerCare";
import WhyChooseUs from "./WhyChooseUs";
import styles from "./AboutUs.module.css";


function AboutUs() {
  return (
    <div className={styles.aboutUsPage}>
      <Header />
      
      <main className={styles.mainContent}>
       <div className={styles.rectangle}>
        <section className={styles.heroSection}>
          <h1 className={styles.pageTitle}>ABOUT US</h1>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/5c8be98f7420b412924ebb2b978f15fc2011b2fa5a0c37a7c6b5d1a562ac1225?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
            alt="About Us hero image"
            className={styles.heroImage}
          />
         
        </section>
      </div> 
        <WhoWeAre />
        <OurMission />
        <CustomerCare />
        <WhyChooseUs />
      </main>
      <Footer />
      
    </div>
  );
}

export default AboutUs;
