/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NavigationBar from "./NavigationBar";
import styles from "./MainComponent.module.css";

const MainComponent = () => {
  return (
    <main className={styles.mainContainer}>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d7631dd8e1925ceebb8d1bb9647d4d30fd9dfb8dc8bb1a6b575b698dd7a1f3f0?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
        alt=""
        className={styles.backgroundImage}
      />
      <div className={styles.contentWrapper}>
        <NavigationBar />
        <div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/65f6573ad55f6ee9ebe2f817ae3c1556927441f32d49e05b40821d6606da5268?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
          alt="Featured content"
          className={styles.featureImage}
        />
        </div>
      </div>
    </main>
  );
};

export default MainComponent;
