/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./NavigationBar.module.css";

const NavigationBar = () => {
  const navItems = ["HOME", "PRODUCT", "ABOUT US", "CONTACT US", "LOGIN"];

  return (
    <nav className={styles.nav}>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/433d9935cc37859139458f859a43fdea705ce75e2cb8a8582f6f673a21458217?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
        alt="Company Logo"
        className={styles.logo}
      />
      <div className={styles.navLinks}>
        {navItems.map((item, index) => (
          <div
            key={index}
            className={`${styles.navItem} ${
              index === 0 ? styles.activeNavItem : ""
            }`}
            tabIndex="0"
            role="button"
          >
            {item}
          </div>
        ))}
      </div>
    </nav>
  );
};

export default NavigationBar;
