/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./NavigationBar.module.css";
import NavItem from "./NavItem";

const navItems = [
  { text: "HOME", isHome: true },
  { text: "PRODUCT" },
  { text: "ABOUT US" },
  { text: "CONTACT US" },
  { text: "LOGIN" },
];

const NavigationBar = () =>  {
  return (
    <nav className={styles.nav}>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/433d9935cc37859139458f859a43fdea705ce75e2cb8a8582f6f673a21458217?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
        className={styles.logo}
        alt="Company logo"
      />
      <div className={styles.navLinks}>
        {navItems.map((item, index) => (
          <NavItem key={index} text={item.text} isHome={item.isHome} />
        ))}
      </div>
      <div className={styles.cartIcon}>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/fb5972a1a2b72c74da874c746fd306d9874fe3b026f215fd9f7c46b0758102f4?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
          className={styles.cartImage}
          alt="Shopping cart"
        />
      </div>
    </nav>
  );
};

export default NavigationBar;
